FROM python:3.14-slim

WORKDIR /service

COPY car-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY car-api/ .

EXPOSE 8003

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003"]
