FROM python:3.14-slim

WORKDIR /service

COPY cache-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY cache-service/ .

EXPOSE 8002

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"]
